# Utilisez une image MongoDB officielle
FROM mongo

# MÉTADONNÉES DE L'IMAGE
LABEL version="1.0" maintainer="CHETOUI IFTIKHAR <chetouiiftikhar@gmail.com>"

# Définissez le port d'écoute par défaut
EXPOSE 27017

# Vous pouvez ajouter des paramètres de configuration MongoDB ici
